// ===============================================================
//                     CLUBS & CAMPS DATA TYPES
// ===============================================================
//
// These declarations model Airtable rows returned by airTableSelect()
// and data structures used by BookingForm, BookingDetails, and server
// handlers for POST /clubPayment, /clubBooking, /campPayment, /campBooking.
//
// All shapes correspond exactly to fields created/consumed in the
// refactored Nuxt 4 / Nitro setup.
//


//
// ============================
//        CLUBS DOMAIN
// ============================
//

// Raw Airtable record (flattened via airtableSelect)
export interface ClubRecord {
  id: string;
  
  clubName: string;
  yearRange: string[];            // e.g. "R-6"
  clubRef: string;              // unique code for the club (e.g. "PF-mon-pm-1")
  schoolName: string;
  schoolRef: string;            // unique code for the school (e.g. "PF")

  startDate: string;            // ISO date string
  endDate: string;              // ISO date string

  sessions: number;             // number of sessions per term
  pricePerSession: number;      // £ per session
  termCost: number;             // sessions * pricePerSession

  spaceAvailable: number;       // TODO should be reduced as bookings are made

  status?: string | null;       // e.g. "upcoming", "current"
}

// Client/UI-friendly club with index marker for lists
export interface ClubOption extends ClubRecord {
  index: number;
}

// Raw school record from Airtable
export interface SchoolRecord {
  id: string;                 // Airtable record ID
  schoolName: string;         // full name of the school  (e.g. "Portfield Primary Academy")
  schoolRef: string;          // unique code for the school (e.g. "PF")
  status?: string | null;     // e.g. "space", "full"
}

export interface SchoolOption extends SchoolRecord {
  index: number;
}

// Record created by POST /api/clubs/clubPayment
export interface ClubPaymentRecord {
  id: string;

  paymentRef: string;           // generated by frontend
  status: string;               // "awaiting payment", etc.

  surname: string;          // child's surname
  childName: string;        // child's first name
  parentName: string;       // main parent/guardian full name
  contactNumber: string;    // main contact number    
  email: string;

  clubsBooked: string;          // JSON string of clubRefs or names
  clubsQty: number;            // number of clubs booked  
  amountDue: number;        // total amount due for all booked clubs

  school: string;            // schoolName
  yearGroup: string;      // e.g. "3"
  medicalConds: string;
}

// Record created by POST /api/clubs/clubBooking
export interface ClubBookingRecord {
  id: string;

  club: string;                 // clubName
  paymentRef: string;
  bookingRef: string;           // generated "paymentRef-clubRef"

  surname: string;
  childName: string;
  parentName: string;
  contactNumber: string;
  email: string;

  altParentName?: string;
  altParentContact?: string;

  medicalConds: string;
  yearGroup: string;
  school: string;

  startDate: string;
  endDate: string;

  sessionCost: number;
  sessionsPerTerm: number;
  termCost: number;

  status: string;               // "reserved awaiting payment"
  clubRef: string;
  sessions: number;
}



//
// ============================
//        CAMPS DOMAIN
// ============================
//

// Raw Airtable record for camps (flattened)
export interface CampRecord {
  id: string;

  campName: string;
  campRef: string;              // unique camp code
  campDate: string;             // for display; may duplicate ws or provide additional context
  locRef: string;               // location reference
  ws: string;                   // week starting ("weekStarting")

  pricePerDay: number;
  spaceAvailable: number;

  status?: string | null;       // "current", "past", etc.
  haf?: boolean;                // HAF-eligible?

  daysAvailable?: string[] | null;  // e.g. ["Mon","Tue","Wed"]
  hafDays?: string[] | null;        // alternative days array for HAF bookings
}

// Client/UI-friendly camp entry
export interface CampOption extends CampRecord {
  index: number;
  weekStarting: string;         // alias of ws for clarity in components
}

// Item added to the booking summary (client-side)
export interface CampBookingItem {
  campName: string;
  campRef: string;
  locRef: string;

  weekStarting: string;
  campDate: string;

  daysSelected: string[];
  isHaf: boolean;

  pricePerDay: number;
  termCost: number;
}

// Record created at POST /api/camps/campPayment
export interface CampPaymentRecord {
  id: string;

  paymentRef: string;

  parentName: string;
  mainContact: string;
  altContact?: string;
  email: string;

  childrenSummary: string;      // JSON or string summarising children
  campsSummary: string;         // JSON of CampBookingItem[]
  amountDue: number;
  status: string;               // "awaiting payment"
}

// Record created at POST /api/camps/campBooking
export interface CampBookingRecord {
  id: string;

  campName: string;
  campRef: string;
  locRef: string;

  weekStarting: string;
  campDate: string;

  daysSelected: string[];
  isHaf: boolean;

  pricePerDay: number;
  termCost: number;

  parentName: string;
  mainContact: string;
  email: string;
  childName: string;

  bookingRef: string;
  paymentRef: string;

  status: string;               // "reserved awaiting payment"
}
